# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2519e52ca55025242874e98f1e7961bfd75e7660f7094d63c2f011f790e2aa3165c043be70b07977839ce7c40a41109ffaa77525a1b64eb1209b42562e6cfe7f

test:
  secret_key_base: 934960e70f8f9613637a5a89b3c25c8a3540b51667338cf685eda94cfe34240aaf1ba7bdc1b7b5dc838cc9225db09d762021b0454ab52fbb338b18c6d891306e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
